
services:
  plants_back:
    build: backend
    ports:
     - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db_plants:3306/angular_java?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 12345
    restart: always
    depends_on:
      db_plants:
        condition: service_healthy
  db_plants:
    image: mysql:8.3.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: angular_java
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  plants_front:
    build: appFront
    ports:
      - "4200:4200"
    depends_on:
      - plants_back